apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone-app
  labels:
    app: udacity-devops-capstone-app
spec:
  type: LoadBalancer
  selector:
    app: udacity-devops-capstone-app
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP