version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0

parameters:
  skip-build:
    type: boolean
    default: false
    description: should skip build workflow
  create-cluster:
    type: boolean
    default: false
    description: create new cluster if true
  deploy-cluster:
    type: boolean
    default: false
    description: continue deploy to cluster

commands:
  install-eksctl:
    steps:
      - run:
          name: Install the eksctl tool
          description: |
            Fixed version of install-eksctl command, which have incorrect eksctl download url
            Original version: https://github.com/CircleCI-Public/aws-eks-orb/blob/master/src/commands/install-eksctl.yml
            Should be fixed in orb circleci/aws-eks@2.0.0
          command: |
            if which eksctl > /dev/null; then
              echo "eksctl is already installed"
              exit 0
            fi

            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
              | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
              SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download


jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - run:
          name: Lint
          command: |
            hadolint Dockerfile
  check-if-cluster-exists:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster to be checked
        type: string
    steps:
      - install-eksctl
      - run:
          shell: /bin/bash
          name: Determine if a cluster creation is needed
          command: |
            CLUSTER_VAR="<< parameters.cluster-name >>"
            CLUSTER_NOT_EXIST=$(eksctl get cluster $CLUSTER_VAR 2>&1 >/dev/null )

            echo "CIRCLECI_API_KEY - $CIRCLECI_API_KEY"
            echo "CIRCLE_PROJECT_USERNAME - $CIRCLE_PROJECT_USERNAME"
            echo "CIRCLE_PROJECT_REPONAME - $CIRCLE_PROJECT_REPONAME"
            echo "CIRCLE_BRANCH - $CIRCLE_BRANCH"

            if [ ! -z "$CLUSTER_NOT_EXIST" ]; then
              printf "\nTriggering cluster-creation workflow\n"
              curl -X POST -u ${CIRCLECI_API_KEY}: \
                --url https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline \
                --header "Content-Type: application/json" \
                --data '{ "branch": "${CIRCLE_BRANCH}", "parameters": { "create-cluster": true, "skip-build": true } }'
            else
              printf "\nTriggering cluster-test workflow\n"
              curl -X POST -u ${CIRCLECI_API_KEY}: \
                --url https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline \
                --header "Content-Type: application/json" \
                --data '{ "branch": "${CIRCLE_BRANCH}", "parameters": { "skip-build": true, "deploy-cluster": true } }'
            fi

  create-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster to be created
        type: string
        default: ''
    steps:
      - install-eksctl
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          verbose: 4
          tags: "Project=UdacityCapstone"
          node-type: "t2.micro"
          nodes-max: 2
          ssh-access: true
          ssh-public-key: "udacity_aws"
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
          name: Test cluster
  go-to-deployment-workflow:
      executor: aws-eks/python3
      steps:
        - run:
            name: Start deploy-cluster workflow
            command: |
              curl -X POST -u ${CIRCLECI_API_KEY}: \
                              --url https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline \
                              --header "Content-Type: application/json" \
                              --data '{ "branch": "${CIRCLE_BRANCH}", "parameters": { "skip-build": true, "deploy-cluster": true, "skip-build": true } }'
  start-deployment:
      executor: aws-eks/python3
      steps:
        - run:
            name: Start deployment
            command: |
              echo "SUCCESS"
  delete-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster to be deleted
        type: string
    steps:
      - install-eksctl
      - aws-eks/delete-cluster:
          cluster-name: << parameters.cluster-name >>
          verbose: 4

workflows:
  build:
    unless: << pipeline.parameters.skip-build >>
    jobs:
      - lint
  check-cluster-existence:
    unless: << pipeline.parameters.create-cluster >>
    jobs:
      - check-if-cluster-exists:
          cluster-name: my-eks-demo
  cluster-creation:
    when: << pipeline.parameters.create-cluster >>
    jobs:
      - create-cluster:
          cluster-name: my-eks-demo
      - test-cluster:
          cluster-name: my-eks-demo
      - go-to-deployment-workflow
  deployment:
    when: << pipeline.parameters.deploy-cluster >>
    jobs:
      - approve-deployment:
          type: approval
      - start-deployment:
          requires:
            - approve-deployment
      #- delete-cluster:
      #    cluster-name: my-eks-demo
      #    requires:
      #     - test-cluster
